apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: robofleet-alerts
  labels: { role: alert-rules }
spec:
  groups:
  - name: robofleet.slo
    rules:
    - alert: HighErrorRate
      expr: sum(rate(http_requests_total{status=~"5..", app="ingestor"}[5m])) / sum(rate(http_requests_total{app="ingestor"}[5m])) > 0.005
      for: 5m
      labels: { severity: page }
      annotations:
        summary: "Error rate > 0.5%"
    - alert: PubsubAckAgeHigh
      expr: avg(pubsub_subscription_oldest_unacked_message_age{subscription="robofleet-telemetry-sub"}) > 30
      for: 2m
      labels: { severity: page }
      annotations:
        summary: "Pub/Sub ack age > 30s"