name: CI
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  build-scan-sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build images
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/ingestor:pr-${{ github.run_number }} apps/ingestor
          docker build -t ghcr.io/${{ github.repository_owner }}/control-api:pr-${{ github.run_number }} apps/control-api

      - name: Trivy scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/ingestor:pr-${{ github.run_number }}
          format: 'table'
          vuln-type: 'os,library'
          exit-code: '0'

      - name: Generate SBOM (Syft)
        uses: anchore/sbom-action@v0
        with:
          image: ghcr.io/${{ github.repository_owner }}/ingestor:pr-${{ github.run_number }}
          artifact-name: sbom-ingestor-${{ github.run_number }}.spdx.json
