apiVersion: v1
kind: Namespace
metadata:
  name: robofleet
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: robofleet
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/OWNER/gcp-gke-robofleet
    targetRevision: HEAD
    path: charts/ingestor
    helm:
      values: |
        image:
          repository: ghcr.io/OWNER/ingestor
          tag: latest
        env:
          GCP_PROJECT: YOUR_PROJECT
  destination:
    server: https://kubernetes.default.svc
    namespace: robofleet
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: robofleet-control-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/OWNER/gcp-gke-robofleet
    targetRevision: HEAD
    path: charts/control-api
    helm:
      values: |
        image:
          repository: ghcr.io/OWNER/control-api
          tag: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: robofleet
  syncPolicy:
    automated:
      prune: true
      selfHeal: true